#!/usr/bin/env bash
set -euo pipefail

if [[ $# -ne 1 ]]; then
  echo "Usage: $0 <commit-msg-file>" >&2
  exit 2
fi

msg_file="$1"
first_line="$(sed -n '1p' "$msg_file")"

# Allow merge commits generated by git/GitHub.
if [[ "$first_line" =~ ^Merge[[:space:]] ]]; then
  exit 0
fi

# Allow automatic reverts.
if [[ "$first_line" =~ ^Revert[[:space:]]\" ]]; then
  exit 0
fi

# Conventional Commits:
# type(scope)!: subject
# type!: subject
# type: subject
pattern='^(feat|fix|docs|style|refactor|perf|test|build|ci|chore|revert)(\([a-zA-Z0-9._/-]+\))?(!)?: .+'

if [[ "$first_line" =~ $pattern ]]; then
  exit 0
fi

cat >&2 <<'EOF'
ERROR: Commit message must follow Conventional Commits.

Expected:
  <type>[optional scope][!]: <description>

Examples:
  feat(agent): add streaming response parser
  fix: handle null API responses
  refactor!: remove legacy configuration path

Allowed types:
  feat, fix, docs, style, refactor, perf, test, build, ci, chore, revert
EOF
exit 1
